# Principal Component Analysis (PCA)

# Generate dataframe

In [250]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
import math

In [251]:
np.random.seed(42)

fratures = [np.random.random(30) for _ in range(10)]
columns = [ "feature_" + str(i) for i in range(10)]

In [252]:
df = pd.DataFrame(fratures,columns).T

In [253]:
df

feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  \
0    0.374540   0.607545   0.388677   0.119594   0.807440   0.908266   
1    0.950714   0.170524   0.271349   0.713245   0.896091   0.239562   
2    0.731994   0.065052   0.828738   0.760785   0.318003   0.144895   
3    0.598658   0.948886   0.356753   0.561277   0.110052   0.489453   
4    0.156019   0.965632   0.280935   0.770967   0.227935   0.985650   
5    0.155995   0.808397   0.542696   0.493796   0.427108   0.242055   
6    0.058084   0.304614   0.140924   0.522733   0.818015   0.672136   
7    0.866176   0.097672   0.802197   0.427541   0.860731   0.761620   
8    0.601115   0.684233   0.074551   0.025419   0.006952   0.237638   
9    0.708073   0.440152   0.986887   0.107891   0.510747   0.728216   
10   0.020584   0.122038   0.772245   0.031429   0.417411   0.367783   
11   0.969910   0.495177   0.198716   0.636410   0.222108   0.632306   
12   0.832443   0.034389   0.005522   0.314356   0.119865   0.633530   
13   0.212339   0.909320   0.815461   0.508571   0.337615   0.535775   
14   0.181825   0.258780   0.706857   0.907566   0.942910   0.090290   
15   0.183405   0.662522   0.729007   0.249292   0.323203   0.835302   
16   0.304242   0.311711   0.771270   0.410383   0.518791   0.320780   
17   0.524756   0.520068   0.074045   0.755551   0.703019   0.186519   
18   0.431945   0.546710   0.358466   0.228798   0.363630   0.040775   
19   0.291229   0.184854   0.115869   0.076980   0.971782   0.590893   
20   0.611853   0.969585   0.863103   0.289751   0.962447   0.677564   
21   0.139494   0.775133   0.623298   0.161221   0.251782   0.016588   
22   0.292145   0.939499   0.330898   0.929698   0.497249   0.512093   
23   0.366362   0.894827   0.063558   0.808120   0.300878   0.226496   
24   0.456070   0.597900   0.310982   0.633404   0.284840   0.645173   
25   0.785176   0.921874   0.325183   0.871461   0.036887   0.174366   
26   0.199674   0.088493   0.729606   0.803672   0.609564   0.690938   
27   0.514234   0.195983   0.637557   0.186570   0.502679   0.386735   
28   0.592415   0.045227   0.887213   0.892559   0.051479   0.936730   
29   0.046450   0.325330   0.472215   0.539342   0.278646   0.137521   

    feature_6  feature_7  feature_8  feature_9  
0    0.341066   0.548734   0.940459   0.809361  
1    0.113474   0.691895   0.953929   0.810113  
2    0.924694   0.651961   0.914864   0.867072  
3    0.877339   0.224269   0.370159   0.913241  
4    0.257942   0.712179   0.015457   0.511342  
5    0.659984   0.237249   0.928319   0.501516  
6    0.817222   0.325400   0.428184   0.798295  
7    0.555201   0.746491   0.966655   0.649964  
8    0.529651   0.649633   0.963620   0.701967  
9    0.241852   0.849223   0.853009   0.795793  
10   0.093103   0.657613   0.294449   0.890005  
11   0.897216   0.568309   0.385098   0.337995  
12   0.900418   0.093675   0.851137   0.375583  
13   0.633101   0.367716   0.316922   0.093982  
14   0.339030   0.265202   0.169493   0.578280  
15   0.349210   0.243990   0.556801   0.035942  
16   0.725956   0.973011   0.936155   0.465598  
17   0.897110   0.393098   0.696030   0.542645  
18   0.887086   0.892047   0.570061   0.286541  
19   0.779876   0.631139   0.097176   0.590833  
20   0.642032   0.794811   0.615007   0.030500  
21   0.084140   0.502637   0.990054   0.037348  
22   0.161629   0.576904   0.140084   0.822601  
23   0.898554   0.492518   0.518330   0.360191  
24   0.606429   0.195243   0.877373   0.127061  
25   0.009197   0.722452   0.740769   0.522243  
26   0.101472   0.280772   0.697016   0.769994  
27   0.663502   0.024316   0.702484   0.215821  
28   0.005062   0.645472   0.359491   0.622890  
29   0.160808   0.177111   0.293592   0.085347

In [254]:
df.shape

(30, 10)

In [255]:
# Standardization
def stand(x):
    return (x - x.mean()) / x.std()

In [256]:
newdf = stand(df)

In [257]:
newdf

feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  \
0   -0.226825   0.337706  -0.315043  -1.269522   1.188577   1.537721   
1    1.813397  -0.990203  -0.710451   0.758141   1.488393  -0.799221   
2    1.038912  -1.310687   1.168001   0.920519  -0.466685  -1.130057   
3    0.566774   1.374887  -0.422630   0.239083  -1.169972   0.074081   
4   -1.000606   1.425772  -0.678147   0.955297  -0.771294   1.808160   
5   -1.000691   0.948007   0.204015   0.008594  -0.097697  -0.790507   
6   -1.347392  -0.582765  -1.149994   0.107432   1.224340   0.712509   
7    1.514049  -1.211568   1.078557  -0.217704   1.368804   1.025232   
8    0.575472   0.570727  -1.373680  -1.591185  -1.518653  -0.805946   
9    0.954207  -0.170924   1.700980  -1.309494   0.185170   0.908496   
10  -1.480176  -1.137530   0.977615  -1.570657  -0.130491  -0.351122   
11   1.881368  -0.003729  -0.955232   0.495707  -0.791002   0.573314   
12   1.394599  -1.403858  -1.606312  -0.604297  -1.136783   0.577591   
13  -0.801176   1.254666   1.123259   0.059060  -0.400359   0.235964   
14  -0.909226  -0.722033   0.757253   1.421863   1.646732  -1.320887   
15  -0.903633   0.504758   0.831900  -0.826528  -0.449101   1.282734   
16  -0.475749  -0.561199   0.974331  -0.276309   0.212372  -0.515385   
17   0.305088   0.071903  -1.375385   0.902642   0.835428  -0.984594   
18  -0.023556   0.152857  -0.416859  -0.896527  -0.312379  -1.493928   
19  -0.521828  -0.946660  -1.234433  -1.415075   1.744378   0.428587   
20   0.613495   1.437782   1.283817  -0.688336   1.712808   0.731481   
21  -1.059120   0.846931   0.475651  -1.127342  -0.690643  -1.578456   
22  -0.518586   1.346365  -0.509765   1.497454   0.139517   0.153203   
23  -0.255784   1.210628  -1.410725   1.082197  -0.524602  -0.844884   
24   0.061871   0.308400  -0.576883   0.485437  -0.578841   0.618281   
25   1.227229   1.292812  -0.529024   1.298541  -1.417414  -1.027062   
26  -0.846024  -1.239460   0.833919   1.067003   0.519366   0.778217   
27   0.267830  -0.912845   0.523706  -1.040761   0.157883  -0.284889   
28   0.544664  -1.370924   1.365068   1.370604  -1.368065   1.637196   
29  -1.388585  -0.519817  -0.033514   0.164162  -0.599789  -1.155827   

    feature_6  feature_7  feature_8  feature_9  
0   -0.509765   0.174595   1.102914   1.055381  
1   -1.217000   0.739698   1.147166   1.057989  
2    1.303834   0.582066   1.018831   1.255497  
3    1.156683  -1.106167  -0.770650   1.415588  
4   -0.768072   0.819765  -1.935926   0.021985  
5    0.481259  -1.054931   1.063031  -0.012088  
6    0.969871  -0.706974  -0.580023   1.017009  
7    0.155650   0.955206   1.188974   0.502662  
8    0.076253   0.572875   1.179004   0.682985  
9   -0.818069   1.360721   0.815624   1.008331  
10  -1.280302   0.604375  -1.019373   1.335019  
11   1.218448   0.251863  -0.721571  -0.579106  
12   1.228399  -1.621664   0.809471  -0.448768  
13   0.397723  -0.539939  -0.945544  -1.425234  
14  -0.516093  -0.944591  -1.429882   0.254095  
15  -0.484460  -1.028324  -0.157487  -1.626490  
16   0.686264   1.849347   1.088775  -0.136636  
17   1.218120  -0.439748   0.299910   0.130527  
18   1.186971   1.529757  -0.113925  -0.757525  
19   0.853818   0.499873  -1.667458   0.297624  
20   0.425473   1.145940   0.033733  -1.645360  
21  -1.308153  -0.007363   1.265845  -1.621615  
22  -1.067360   0.285791  -1.526497   1.101289  
23   1.222607  -0.047307  -0.283875  -0.502142  
24   0.314839  -1.220743   0.895664  -1.310533  
25  -1.541036   0.860316   0.446887   0.059784  
26  -1.254296  -0.883132   0.303149   0.918872  
27   0.492191  -1.895445   0.321114  -1.002751  
28  -1.553886   0.556452  -0.805695   0.408784  
29  -1.069910  -1.292316  -1.022189  -1.455175

In [258]:
# Covariance Matrix
def coMat(x):
    return np.cov(x.T)

In [259]:
cov = coMat(df)

In [260]:
cov

array([[ 0.079754  , -0.01492926, -0.00970407,  0.00803297, -0.00795922,
         0.00517455,  0.01976306,  0.01890092,  0.03630665,  0.01301234],
       [-0.01492926,  0.10830968, -0.01846831,  0.00793838, -0.0256429 ,
        -0.00347226,  0.00211297,  0.00507083, -0.01441531, -0.02802807],
       [-0.00970407, -0.01846831,  0.08804728, -0.00793968,  0.01117639,
         0.01172478, -0.03474914,  0.01505522,  0.00902347, -0.00529625],
       [ 0.00803297,  0.00793838, -0.00793968,  0.08571759, -0.00772733,
        -0.00469914, -0.01106403, -0.00830523, -0.02448112,  0.01265203],
       [-0.00795922, -0.0256429 ,  0.01117639, -0.00772733,  0.08742977,
         0.00735174,  0.00536358,  0.00906316, -0.00158379,  0.01478564],
       [ 0.00517455, -0.00347226,  0.01172478, -0.00469914,  0.00735174,
         0.08187887, -0.01059775,  0.00065504, -0.0167141 ,  0.00833892],
       [ 0.01976306,  0.00211297, -0.03474914, -0.01106403,  0.00536358,
        -0.01059775,  0.10355921, -0.01081917

In [261]:
# Evalue,Evector
def eigenV(x):
    Evalue,Evector = np.linalg.eig(x)
    #Evector = Evector.T
    return Evalue,Evector

In [262]:
Evalue,Evector=eigenV(cov)

In [263]:
Evalue

array([0.16307655, 0.15036615, 0.02016979, 0.11704867, 0.10723031,
       0.03911653, 0.08626907, 0.07720219, 0.06382984, 0.0503897 ])

In [264]:
def getmatrix(Evalue,Evector,n_com):
    sortV = np.argsort(Evalue)[::-1]
    Evalue = Evalue[sortV]
    Evector = Evector[sortV]
    
    return Evector[:n_com]
    

In [265]:
n_com = 3
mat = getmatrix(Evalue,Evector,n_com)

In [266]:
mat.shape

(3, 10)

In [267]:
mat

array([[-0.22533125,  0.43181644, -0.54841942,  0.09212014,  0.44510545,
         0.32699946,  0.20489747,  0.19962319,  0.25782155, -0.01259238],
       [ 0.6153576 , -0.06730151, -0.22944779, -0.23108688,  0.24017839,
        -0.26865981,  0.44385825, -0.34382586,  0.09620329,  0.237514  ],
       [ 0.1532434 , -0.17003208,  0.32350646,  0.48792316,  0.41842818,
        -0.10523407, -0.28621328,  0.01380182,  0.5665014 ,  0.12526528]])

In [268]:
def transfrom(df,mat):
    return np.dot(df,mat.T)

In [269]:
transfrom(newdf,mat)

array([[ 1.48611046,  0.14617379,  0.4273014 ],
       [ 0.20515299,  1.30968872,  2.43415902],
       [-1.30287053,  1.21311316,  1.50200851],
       [ 0.0229225 ,  1.15286944, -1.26990992],
       [ 1.05587863, -2.25166441, -1.52485167],
       [ 0.38402164,  0.13625075,  0.24635321],
       [ 1.36573526,  0.41108303, -0.47821942],
       [-0.00859449,  0.84381119,  1.85073407],
       [ 0.20940083,  0.96289712, -1.04071511],
       [-0.66120423, -0.20159864,  0.90979276],
       [-1.43271648, -1.1896958 , -0.53662116],
       [ 0.10057529,  1.16583946, -0.99609777],
       [-0.26998278,  2.10675271, -0.87014764],
       [-0.24142946, -1.07567961, -0.97173315],
       [-0.75634175, -0.24435623,  1.10668839],
       [-0.21589872, -1.30532159, -0.84985439],
       [ 0.02328384, -0.48418128,  0.77478333],
       [ 1.08711969,  1.50678551,  0.3147189 ],
       [ 0.11853366,  0.41436632, -1.05343287],
       [ 1.01308768,  0.77404125, -1.46881416],
       [ 1.06206271, -0.23259477,  0.275

# In class format

In [270]:
class PCA():
    
    def __init__(self,n_com):
        self.n_com = n_com
        
    def fit(self,df):
        stan = self._stand(df)
        comM = np.cov(stan.T)
        Evalue,Evector = self._eigenV(comM)
        mat = self._getmatrix(Evalue,Evector,self.n_com)
        
        return np.dot(df,mat.T)

    def _stand(self,df):
        return (df - df.mean()) / df.std()
    
    def _eigenV(self,x):
        Evalue,Evector = np.linalg.eig(x)
        return Evalue,Evector
    
    def _getmatrix(self,Evalue,Evector,n_com):
        sortV = np.argsort(Evalue)[::-1]
        Evalue = Evalue[sortV]
        Evector = Evector[sortV]
    
        return Evector[:n_com] 

In [271]:
model = PCA(6)

In [273]:
pd.DataFrame(model.fit(df))

0         1         2         3         4         5
0  -0.229464  0.104880  1.188121 -0.186995 -1.275237 -0.407506
1  -0.970421 -0.479913  0.818370  0.246399 -1.052060 -0.324495
2  -0.604791 -0.525547  0.746077  0.069711 -1.375029  0.422821
3   0.330329 -0.421329  0.550322  0.060137 -1.604306 -0.035763
4   0.061414 -0.489373  0.664458 -0.194021 -1.455147 -0.601759
5  -0.075843 -0.268360  0.529365 -0.419109 -1.318439 -0.144223
6  -0.188601  0.253131  0.634582  0.222939 -1.332287 -0.487638
7  -0.854072 -0.135775  1.280871  0.100345 -1.394490  0.145664
8  -0.052450 -0.188311  0.627485 -0.514736 -0.968977  0.054701
9  -0.378291 -0.413575  1.507623 -0.201556 -1.129656  0.127651
10 -0.051754 -0.309493  1.154219 -0.001263 -0.472694 -0.165346
11 -0.424070 -0.214190  0.496287  0.074259 -1.572360  0.221160
12 -0.346733  0.303944  0.229694  0.114874 -1.277121  0.478872
13 -0.040081 -0.392580  0.700950 -0.366709 -1.397099 -0.005251
14 -0.492781 -0.541754  0.618866  0.419691 -1.004040 -0.439867
15 -0.073666 -0.093388  0.757321 -0.393615 -1.194298  0.049672
16 -0.655507 -0.249326  0.997619 -0.483989 -1.187040  0.089194
17 -0.505560 -0.119561  0.349387  0.040391 -1.439647 -0.273631
18 -0.441468 -0.179503  0.708460 -0.470860 -1.043112  0.073740
19 -0.365946  0.394668  0.981819  0.272242 -0.984965 -0.384153
20 -0.586513 -0.213222  1.313135 -0.436271 -1.553875 -0.131263
21 -0.285180 -0.449089  0.609403 -0.855438 -0.695624 -0.050100
22 -0.053793 -0.764084  0.645896  0.066085 -1.335207 -0.748612
23 -0.213521 -0.321030  0.189974 -0.305585 -1.525679 -0.269744
24 -0.332727 -0.095645  0.297619 -0.304668 -1.470006  0.050264
25 -0.374322 -1.051838  0.429682 -0.372865 -1.186929 -0.217297
26 -0.414318 -0.381575  0.735128  0.221160 -1.124597 -0.252371
27 -0.321526  0.071732  0.625598  0.029828 -1.036563  0.354694
28 -0.439682 -0.753959  0.809907  0.199858 -1.182564  0.166426
29 -0.239554 -0.376373  0.244670 -0.124293 -0.671998 -0.115300